### ISSUE TITLE
strong name signature not valid  

### ISSUE THREAD

**Issue by ImAreeb** [cydolo/CyberReverse#12]
Hey, I am getting this error while deploying 

`strong name signature not valid for this assembly bunifu.licensing.dll`

**Comment by cydolo** [comment]
Please make sure you have all the requirements bunifu need.

![Screenshot 2021-10-20 204311](https://user-images.githubusercontent.com/25271332/138152627-2c80dea9-0383-43f3-8bcf-dee0abd18a76.jpg)
