### ISSUE TITLE
Bunifu.UI.WinForms 5.3.0

### ISSUE THREAD

**Issue by k3nnk3nn** [cydolo/CyberReverse#14]
plz update the patch to v5.3.0

**Comment by cydolo** [comment]
no patch needed. just update the nuget package and replace the dll.

**Comment by malafalx91** [comment]
No work. Hi have try to replace dll but no work **'System.ComponentModel.LicenseException: 'This product does not have a valid Bunifu UI WinForms license to run.''**

**Comment by HeroinGyrl** [comment]
> 
> 
> No work. Hi have try to replace dll but no work **'System.ComponentModel.LicenseException: 'This product does not have a valid Bunifu UI WinForms license to run.''**

check this first please:
https://github.com/cydolo/CyberReverse/tree/master/Bunifuframework.com#issues

**Comment by cydolo** [comment]
> 
> 
> No work. Hi have try to replace dll but no work **'System.ComponentModel.LicenseException: 'This product does not have a valid Bunifu UI WinForms license to run.''**

this happens during initializing of components the first time. bunifu saves these into a `licenses.licx` stored in properties
![Screenshot 2021-11-15 203924](https://user-images.githubusercontent.com/25271332/141843457-47c6a8ac-c126-442c-9798-04d2bb15763a.jpg)

for me everything works. just rebuild the project. check the steps.
https://github.com/cydolo/CyberReverse/tree/master/Bunifuframework.com#issues
