### ISSUE TITLE
Only online

### ISSUE THREAD

**Issue by markolino85** [cydolo/CyberReverse#16]
Hello and thanks for this project.
I think the license must be verified each time you open a project that contains Bunifu controls. This means that on your development machine must always have an internet connection. Correct ?
You cannot run this on offline development machine.

**Comment by cydolo** [comment]
[Bunifu.Licensing.zip](https://github.com/cydolo/CyberReverse/files/8341937/Bunifu.Licensing.zip)

you can try this file, there I have removed the network checks.

bunifu has not brought any updates for 5 months, try something new maybe you will like blazor.

**Comment by markolino85** [comment]
Thank you !
For now I only use Winforms. 
It can works only with .net or also with .net core ?

**Comment by cydolo** [comment]
> Thank you ! For now I only use Winforms. It can works only with .net or also with .net core ?

bunifu only supports .net framework.
